初回の資料を作成+chapter00の動作確認用コードを追加
kurupeku/hello-golang pull request #22
Opened 2022-10-06 15:24 UTC by kudagonbe

## やったこと

- [x] marp用のmarkdownファイルを作成（`assets/marp/installation.md`）
- [x] marpで出力したHTMLファイルの追加
- [x] `subject/chapter00`配下に動作確認用コードを追加
- [x] CI用ymlファイルを追加

## Reference

- https://github.com/kurupeku/hello-golang/issues/15

Close #15

2022-10-07 01:12 UTC, kurupeku requested changes
すごく細かい所の指摘で恐縮なのですが、いくつかコメント及びサジェストさせて頂きました！

あと可能であればリンターに準拠したいのでリストを `-` で統一して頂けるとありがたいです 🙇

2022-10-07 01:12 UTC, kurupeku commented on assets/marp/installation.md
> +  - vscodeのDevContainers拡張機能を使ってDockerコンテナ上で開発する場合
```suggestion
  - VSCodeのDevContainers拡張機能を使ってDockerコンテナ上で開発する場合
```

2022-10-07 01:12 UTC, kurupeku commented on assets/marp/installation.md
> ++ Dockerコンテナを起動させて、コンテナ上にあるソースコードを直接編集するvscodeの機能
```suggestion
+ Dockerコンテナを起動させて、コンテナ上にあるソースコードを直接編集するVSCodeの機能
```

2022-10-07 01:12 UTC, kurupeku commented on assets/marp/installation.md
> +  + 例えば今回の場合、Goやタスクランナー(go-task)は事前にインストール済み
```suggestion
  + 例えば今回の場合、Goの実行環境やタスクランナー(go-task)、開発用ツールなどが事前にインストール済み
```

2022-10-07 01:12 UTC, kurupeku commented on assets/marp/installation.md
> ++ devcontainer.jsonの設定で、vscodeの拡張機能も共通化できるようになる
```suggestion
+ devcontainer.jsonの値を書き換えれば、vscodeの設定や拡張機能も共通化できるようになる
```

2022-10-07 01:12 UTC, kurupeku commented on assets/marp/installation.md
> +4. ローカル環境でテストを実行してみる
```suggestion
4. cloneしたプロジェクトのルートディレクトリでローカル環境でテストを実行してみる
```

2022-10-07 01:12 UTC, kurupeku commented on assets/marp/installation.md
> +5. vscodeのターミナル上からテストを実行してみる
```suggestion
2. VSCodeをインストールし、cloneしたリポジトリを開く
3. Remote Development拡張をVSCodeにインストール
4. VSCodeの左下の `><` アイコンをクリックし `Reopen in Container` を選択
5. コンテナ上でソースコードが閲覧・編集できることを確認
6. VSCodeのターミナル上からテストを実行してみる
```

2022-10-07 01:12 UTC, kurupeku commented on assets/marp/installation.md
> +  + `task docker-build-test chapter00`
これは Docker 上でテストを実行するコマンドなので、ローカルで実行するパターンと併記頂けるとありがたいです！

```suggestion
  - ローカルで実行する場合
    - `task test -- subject/chapter00`
  - Docker上で実行する場合
    - `task docker-build` (初回のみ)
    - `task docker-test -- subject/chapter00`
```

2022-10-07 02:28 UTC, kurupeku commented
追加で、

- 別ブランチに解答が乗ってるが、早く正解することが目的ではないので閲覧は控える

という注意点を進め方のあたりに注意書きとして加えて頂けますと 🙏

2022-10-07 08:14 UTC, kudagonbe commented
・Goのローカルインストール手順をコマンドで記載する
・DevContainerの場合はGoのインストール不要である旨を記載する
・事前に問題を解いておくのは控えてもらう

2022-10-07 23:18 UTC, kudagonbe commented
@kurupeku 
以下修正を行いました！

- リスト表記をハイフンに統一（https://github.com/kurupeku/hello-golang/pull/22/commits/ccc8240027f53ae2d4f2354543f07cf71c382cbd）
- Goインストール手順を追加（https://github.com/kurupeku/hello-golang/pull/22/commits/a40a8dbcd9a8658b6d3babc74aed9c9c7d158eda）
- 事前に問題を解かない、解答ブランチは見ないというルール追加（https://github.com/kurupeku/hello-golang/pull/22/commits/79c45ad9642a3e4a258a67db8e381427fc613bcb）

2022-10-08 14:50 UTC, kurupeku commented
すみません、ジャストアイデアですが思いついてしまったので相談したいのですが、Goのメソッドの中身を課題と同じようにブランクにしておいて

- チェックアウト
- 実装
- ローカルでテスト回して確認
- プッシュしてCIのUI確認

までを実演するのはどうでしょう？

2022-10-08 16:38 UTC, kudagonbe commented
@kurupeku 
ナイスアイディアですね！やりましょう！
早速ですが、スライドの最後に「実演」というページを追加したのと、サンプルの関数をゼロ値が返ってくるように変更してTODOコメントを付けました。
（テスト通っていないのはそのためです）

2022-10-09 01:32 UTC, kurupeku approved these changes
パーフェクトです！
ありがとうございます 🙇 
![LGTM](https://image.lgtmoon.dev/144735)

2022-10-09 01:33 UTC, merged