marpをちょっとお洒落にしてみました
kurupeku/hello-golang pull request #23
Opened 2022-10-09 02:43 UTC by chmikata

文字の色をGoっぽい感じにして、背景画像にGpoher突っ込んでみました
完全におまけのジャンルなので良さそうなら取り込んでください

2022-10-09 03:14 UTC, kurupeku requested changes
おっしゃーでいい感じだと思います！
ただ、MarpでHTML化する際にインラインHTMLをタグごと文字列として出力してしまうようですので、コメント内容の修正をお願いしたいです！

あと、HTMLの出力を行ってからプッシュいただけますとありがたいです 🙏 
`task marp -- installation.md`

2022-10-09 03:14 UTC, kurupeku commented on assets/marp/installation.md
> +</div>
HTML化した際にインラインHTMLタグはそのまま文字列として処理されてしまうようなので、スポットディレクティブでクラスを定義してスタイリングして頂けるとありがたいです 🙏 

[参考](https://marpit.marp.app/directives?id=class)

```suggestion
<!-- _class: cover -->
# Go勉強会ガイダンス

## インフラ開発部 SRE課（今本/上村)
```

2022-10-09 03:14 UTC, kurupeku commented on assets/marp/installation.md
> +  }
```suggestion
  .cover h1 {
    text-align: center;
    font-size: 60px;
    color: #66CCFF;
    font-weight: bold;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
  }

  .cover h2 {
    text-align: right;
    font-size: 40px;
    color: #ffffff;
    font-weight: bold;
    position: absolute;
    bottom: 20%;
    right: 3%;
  }
```

↓ と合わせてご修正をお願いします 🙏

2022-10-09 03:32 UTC, chmikata commented on assets/marp/installation.md
> +  }
りょ！
ちょいと飲みに行ってくるから後でキレイにしやす！
暇あったらhtml出力のやり方おせーて！

2022-10-09 03:38 UTC, kurupeku commented on assets/marp/installation.md
> +  }
かしこまりました！

HTML出力は

```bash
# go-task を未インストールの場合
go install github.com/go-task/task/v3/cmd/task@latest
# or
brew install go-task/tap/go-task

# HTMLの出力コマンド 
task marp -- installation.md
```

を実行してもらえれば可能です！

2022-10-09 03:48 UTC, chmikata commented on assets/marp/installation.md
> +  }
ざっす！
task用のyamlも確認しときゃっす！

2022-10-10 03:28 UTC, chmikata commented on assets/marp/installation.md
> +</div>
marp側にhtmlで書き込みするかの設定があるのでそれをtrueにしようかと思います！
細かい装飾でその方が小回りが利きそうです！

2022-10-10 03:32 UTC, chmikata commented on assets/marp/installation.md
> +  }
ちょこっとtsak用のyamlも手直ししてみやした！
mvこけてたっぽいのと、imgの画像をhtmlと一緒に移動する感じで

2022-10-10 04:39 UTC, kurupeku approved these changes
オッシャーで非常に良きかな
![LGTM](https://image.lgtmoon.dev/136386)

2022-10-10 04:39 UTC, merged